config/routes.rb
Rails.application.routes.draw do
  resources :policies

  get "/healthcheck" => Proc.new { [200, {}, ["OK"]] }

  root to: "policies#index"
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  validates :content_id, presence: true, uniqueness: true
  validates :name, :slug, presence: true, uniqueness: true
  validates :description, presence: true
  validates :email_alert_signup_content_id, presence: true, uniqueness: true

  validate :applicable_to_at_least_one_nation
  validate :alternative_urls_are_valid

  has_many :policy_relations
  has_many :related_policies, class_name: 'Policy', through: :policy_relations, source: :related_policy

  has_many :inverse_policy_relations, class_name: 'PolicyRelation', foreign_key: 'related_policy_id'
  has_many :parent_policies, through: :inverse_policy_relations, source: :policy

  before_validation on: :create do |object|
    object.slug = object.name.to_s.parameterize
    object.content_id = SecureRandom.uuid
    object.email_alert_signup_content_id = SecureRandom.uuid
  end

  scope :areas, -> {
    joins("LEFT OUTER JOIN policy_relations
              ON policies.id = policy_relations.related_policy_id
              WHERE policy_relations.related_policy_id IS NULL")
  }

  # Virtual attribute used to identify a new record as a sub-policy
  attr_writer :sub_policy
  def sub_policy
    @sub_policy || parent_policies.any?
  end
  alias_method :sub_policy?, :sub_policy

  # TODO remove delegation
  delegate :organisation_content_ids,
           :organisation_content_ids=,
           :lead_organisation_content_ids,
           :lead_organisation_content_ids=,
           :people_content_ids,
           :people_content_ids=,
           :working_group_content_ids,
           :working_group_content_ids=,
           :set_organisation_priority,
           :supporting_organisation_content_ids,
           to: :policy_linkset

  def policy_linkset
    @policy_linkset ||= PolicyLinkset.new(content_id)
  end

  def base_path
    "/government/policies/#{slug}"
  end

  def possible_nations
    [
      :england,
      :northern_ireland,
      :scotland,
      :wales,
    ]
  end

  def applicable_nations
    possible_nations.select { |n| self.send(n) == true }
  end

  def inapplicable_nations
    possible_nations - applicable_nations
  end

private

  def applicable_to_at_least_one_nation
    if applicable_nations.empty?
      errors.add(:applicability, "must have at least one nation")
    end
  end

  def alternative_urls_are_valid
    alt_policy_urls = inapplicable_nations.select { |nation|
      self.send(:"#{nation}_policy_url").present?
    }

    nations_with_bad_urls = alt_policy_urls.reject { |nation|
      self.send(:"#{nation}_policy_url") =~ /\A#{URI::regexp(%w(http https))}\z/
    }

    nations_with_bad_urls.each do |nation|
      errors.add(nation, "must have a valid alternative policy URL")
    end
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :clean_blank_parameters, only: [:create, :update]

  def index
    @policies = Policy.includes(:parent_policies).order(:name)
  end

  def new
    @policy_form = PolicyForm.new
    @policy_form.sub_policy = true if params[:sub_policy]
  end

  def create
    policy_form = PolicyForm.new(policy_params)

    if policy_form.save
      flash[:success] = "Successfully created a policy"
      redirect_to policies_path
    else
      flash[:danger] = "Could not create the policy : #{policy_form.error_messages}"
      @policy_form = policy_form
      render :new
    end
  end

  def edit
    @policy_form = PolicyForm.from_existing(policy)
  end

  def update
    policy_form = PolicyForm.from_existing(policy)
    if policy_form.update(policy_params)
      flash[:success] = "Successfully updated the policy"

      redirect_to policies_path
    else
      flash[:danger] = "Could not update the policy: #{policy_form.error_messages}"

      @policy_form = policy_form
      render :new
    end
  end

private

  def policy
    @policy ||= Policy.find(params[:id])
  end

  def policy_params
    params.require(:policy).permit(
      :description,
      :england_policy_url,
      :england,
      :name,
      :northern_ireland_policy_url,
      :northern_ireland,
      :scotland_policy_url,
      :scotland,
      :sub_policy,
      :wales_policy_url,
      :wales,
      lead_organisation_content_ids: [],
      parent_policy_ids: [],
      people_content_ids: [],
      supporting_organisation_content_ids: [],
      working_group_content_ids: [],
    )
  end

  # Rails includes a hidden field for selects on multi-selects so that a value
  # gets submitted even when nothing is selected. This results in a blank string
  # being included in the resulting parameter array. We clean this out to prevent
  # blank strings being stored.
  def clean_blank_parameters
    params[:policy][:lead_organisation_content_ids].reject!(&:blank?)
    params[:policy][:supporting_organisation_content_ids].reject!(&:blank?)
    params[:policy][:people_content_ids].reject!(&:blank?)
    params[:policy][:working_group_content_ids].reject!(&:blank?)
  end
end

app/views/policies/_form.html.erb
<%= form_for policy_form do |form| %>
  <%= form.hidden_field :sub_policy %>

  <%= form.text_field :name %>
  <%= form.text_area :description %>

  <%= form.select :lead_organisation_content_ids,
        prioritise_data_container(organisations_data_container, policy_form.lead_organisation_content_ids),
        { label: "Organisations" },
        { multiple: true,
          class: 'select2',
          data: { placeholder: 'Choose organisations…' } } %>

  <%= form.select :supporting_organisation_content_ids,
        prioritise_data_container(organisations_data_container, policy_form.supporting_organisation_content_ids),
        { label: "Supporting organisations" },
        { multiple: true,
          class: 'select2',
          data: { placeholder: 'Choose supporting organisations…' } } %>

  <%= form.select :people_content_ids,
        prioritise_data_container(people_data_container, policy_form.people_content_ids),
        { label: "People" },
        { multiple: true,
          class: 'select2',
          data: { placeholder: 'Choose people…' } } %>

  <%= form.select :working_group_content_ids,
        prioritise_data_container(working_groups_data_container, policy_form.working_group_content_ids),
        { label: "Working groups" },
        { multiple: true,
          class: 'select2',
          data: { placeholder: 'Choose working groups…' } } %>

  <%= form.select :parent_policy_ids,
        policies_areas_data_container,
        { label: "Part of" },
        { multiple: true,
          class: 'select2',
          data: { placeholder: 'Choose parent policies…' } } %>

  <h4>Applicable nations</h4>

  <div class="applicable-nations">
    <% form.object.possible_nations.each do |n| %>
      <%= form.check_box(n, data: {nation: n}, label: n.to_s.titlecase) %>
      <%= form.text_field "#{n}_policy_url",
          label:  "#{n.to_s.titlecase} policy url",
          wrapper_html_options: {
            style: form.object.send(n) ? "display: none;" : nil,
            class: "js-alternative-policy-url",
            id: n
          }
      %>
    <% end %>
  </div>

  <%= form.buttons(cancel_link: policies_path) %>
<% end %>

app/views/policies/edit.html.erb
<%= content_for :page_title, "Edit #{policy_type(@policy_form)}" %>

<h1>Edit <%= policy_type(@policy_form) %> </h1>

<%= render "form", policy_form: @policy_form %>

app/views/policies/index.html.erb
<%= content_for :page_title, "Policies" %>

<h1>Policies</h1>

<p>
  <%= link_to "New policy", new_policy_path, class: 'btn btn-primary' %>
  <%= link_to "New sub-policy", new_policy_path(sub_policy: true), class: 'btn btn-primary' %>
</p>

<table class="table table-striped table-bordered" data-module="filterable-table">
  <thead>
    <tr class="table-header">
      <th>Name</th>
      <th>Last updated</th>
      <th>Part of</th>
    </tr>
    <tr class="if-no-js-hide table-header-secondary">
      <td colspan="4">
        <form>
          <label for="table-filter" class="rm">Filter policies</label>
          <input id="table-filter" type="text" class="form-control normal js-filter-table-input" placeholder="Filter policies">
        </form>
      </td>
    </tr>
  </thead>

  <tbody>
    <% @policies.each do |policy| %>
      <tr>
        <td><%= link_to policy.name, edit_policy_path(policy) %></td>
        <td><%= policy.updated_at.to_s(:govuk_date) %></td>
        <td><%= policy.parent_policies.map(&:name).to_sentence %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/policies/new.html.erb
<%= content_for :page_title, "New #{policy_type(@policy_form)}" %>

<h1>New <%= policy_type(@policy_form) %> </h1>

<%= render "form", policy_form: @policy_form %>